---
- name: "Default var"
  hosts: web1
  become: yes

  vars:
    files:
      - { name: "file1", owner: "ansible-learning" }
      - { name: "file2", owner: "ansible-learning", mode: "0666" }
      - { name: "file3", mode: "0666" }
      - { name: "dir1", state: "directory" }
  tasks:
    - name: "Create files"
      file:
        path: "/home/ansible-learning/{{ file.name }}"
        mode: "{{ file.mode | default(omit) }}"
        state: "{{ file.state | default('touch') }}"
        owner: "{{ file.owner | default(omit) }}"
      loop: "{{ files }}"
      loop_control:
        loop_var: file