---
- name: "Create directory"
  file:
    path: "{{ site.root_path }}"
    state: directory
- name: "Generate index.html"
  template:
    src: index.html.j2
    dest: "{{ site.root_path }}/index.html"
- name: "Generate site conf"
  template:
    src: site.conf.j2
    dest: "/etc/nginx/conf.d/mysite.conf"
  notify: "Restart nginx"