---
- name: "Image Template"
  hosts: localhost

  vars:
    engine_fqdn: zvirt-manager.uruk.local
    engine_user: admin@internal
    engine_password: admin

    qcow_url: https://repo.almalinux.org/almalinux/8/cloud/x86_64/images/AlmaLinux-8-GenericCloud-latest.x86_64.qcow2
    # qcow_url: https://cloud.debian.org/images/cloud/bullseye/20230601-1398/debian-11-generic-amd64-20230601-1398.qcow2

    template_cluster: Default
    template_name: Alma8Template
    template_operating_system: rhel_8x64
    template_memory: 2GiB
    template_cpu: 2
    template_disk_size: 30GiB
    template_disk_storage: hosted_storage
    template_prerequisites_tasks: prereq_tasks.yaml
    image_cache_download: true
  roles:
    - ovirt.image-template
