---
- name: "zVirt Infra"
  hosts: localhost

  vars:
    engine_fqdn: zvirt-manager.uruk.local
    engine_user: admin@internal
    engine_password: admin
    data_center_name: Default
    compatibility_version: 4.6

    clusters:
      - name: "Dev"
        cpu_type: "AMD EPYC"
        profile: development
        state: present
      - name: "Staging"
        cpu_type: "AMD EPYC"
        profile: development
        state: present
      - name: "Production"
        cpu_type: "AMD EPYC"
        profile: production
        state: present

    hosts:
      - name: zvirt-host2.uruk.local
        address: zvirt-host2.uruk.local
        cluster: Dev
        password: root
        state: present
      - name: zvirt-host3.uruk.local
        address: zvirt-host3.uruk.local
        cluster: Staging
        password: root
        state: present
      - name: zvirt-host4.uruk.local
        address: zvirt-host4.uruk.local
        cluster: Production
        password: root
        state: present

    storages: 
      host2_share:
        state: present
        nfs:
          address: zvirt-host2.uruk.local
          path: /nfs/host2_share
      host3_share:
        state: present
        nfs:
          address: zvirt-host3.uruk.local
          path: /nfs/host3_share
      host4_share:
        state: present
        nfs:
          address: zvirt-host4.uruk.local
          path: /nfs/host4_share

    logical_networks:
      - name: "DevNetwork"
        state: present
        clusters:
          - name: Dev
            assigned: yes
            required: no
            display: no
            migration: yes
            gluster: no
      - name: "StagingNetwork"
        state: present
        clusters:
          - name: "Staging"
            assigned: yes
            required: no
            display: no
            migration: yes
            gluster: no
      - name: "ProductionNetwork"
        state: present
        clusters:
          - name: "Production"
            assigned: yes
            required: no
            display: no
            migration: yes
            gluster: no

    host_networks:
      - name: zvirt-host1.uruk.local
        save: true
        bond:
          name: bond0
          mode: 4
          interfaces:
            - ens160
            - ens192
        networks:
          - name: "ovirtmgmt"
            boot_protocol: dhcp
      - name: zvirt-host2.uruk.local
        state: present
        save: true
        interface: ens192
        networks:
          - name: "DevNetwork"
            boot_protocol: dhcp
      - name: zvirt-host3.uruk.local
        state: present
        save: true
        interface: ens192
        networks:
          - name: "StagingNetwork"
            boot_protocol: dhcp
      - name: zvirt-host4.uruk.local
        state: present
        save: true
        interface: ens192
        networks:
          - name: "ProductionNetwork"
            boot_protocol: dhcp

    users:
      - name: myuser2
        authz_name: internal-authz
        password: P@$$w0rd123
        valid_to: "2023-01-01 00:00:00Z"
      - name: myuser3
        authz_name: internal-authz
        password: P@$$w0rd123
        valid_to: "2023-01-01 00:00:00Z"
      - name: myuser4
        authz_name: internal-authz
        password: P@$$w0rd123
        valid_to: "2023-01-01 00:00:00Z"
    user_groups:
      - name: mygroup
        authz_name: internal-authz
        users:
          - myuser2
          - myuser3
          - myuser4

    permissions:
      - state: present
        user_name: myuser2
        authz_name: internal-authz
        role: SuperUser
        object_type: host
        object_name: zvirt-host2.uruk.local
      - state: present
        user_name: myuser3
        authz_name: internal-authz
        role: SuperUser
        object_type: host
        object_name: zvirt-host3.uruk.local
      - state: present
        user_name: myuser4
        authz_name: internal-authz
        role: SuperUser
        object_type: host
        object_name: zvirt-host4.uruk.local

  pre_tasks:
    - name: "Login"
      ovirt_auth:
        hostname: "{{ engine_fqdn }}"
        username: "{{ engine_user }}"
        password: "{{ engine_password }}"
      tags:
        - always

  roles:
    - ovirt.infra

  post_tasks:
    - name: "Logout"
      ovirt_auth:
        ovirt_auth: "{{ ovirt_auth }}"
        state: absent
      tags:
        - always
