---
- name: "Test Connection"
  hosts: localhost
  gather_facts: false

  tasks:
    - name: "Login"
      ovirt_auth:
        hostname: zvirt-manager.uruk.local
        username: admin@internal
        password: admin
    - name: "Debug"
      debug:
        var: ovirt_auth
    - name: "Logout"
      ovirt_auth:
        ovirt_auth: "{{ ovirt_auth }}"
        state: absent