---
- name: "Hosts Info"
  hosts: localhost
  gather_facts: false

  tasks:
    - name: "Login"
      ovirt_auth:
        hostname: "zvirt-manager.uruk.local"
        username: ansible@internal
        password: Ansible!@34
    - block:
        - name: "Gather Facts"
          ovirt.ovirt.ovirt_host_info:
            auth: "{{ ovirt_auth }}"
            pattern: name=zvirt-host*
          register: host_info
        - name: "Set relevant information"
          set_fact:
            relevant_host_info: "{{ host_info | json_query(query) }}"
          vars:
            query: "ovirt_hosts[*].{address:address,iname:iscsi.initiator}"
        - name: "Write hosts info to file"
          lineinfile:
            path: /home/urukambas/learnorionsoft/hosts_info.log
            line: "{{ relevant_host_info | to_nice_yaml }}"
            create: true
      always:
        - name: "Logout"
          ovirt_auth:
            ovirt_auth: "{{ ovirt_auth }}"
            state: absent
